name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "truefin.official@gmail.com"
          git config --global user.name "truefinofficial"
          git remote add huggingface https://truefinofficial:$HF_TOKEN@huggingface.co/spaces/truefinofficial/TrueFin
          git push huggingface main --force
